

apiVersion: v1
kind: Service
metadata:
  name: genfract
  labels:
    name: genfract
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  selector:
    name: genfract